from time import sleep
square = float(input('Введите площадь в метрах квадратных: '))
print('Подождите,', end=' ')
sleep(1)
print('выполняется', end=' ')
sleep(1)
print('преобразование', end=' ')
sleep(1)
print('квадратных метров', end=' ')
sleep(1)
print('в акры', end='')
sleep(1)
print('.', end='')
sleep(1)
print('.', end='')
sleep(1)
print('.')
print(f'Площадь в акрах примерно составит: {square / 4040:.2f}')